## Vanessa Williams
## Week 9

In [1]:
import numpy as np
import pandas as pd
import random
from tempfile import NamedTemporaryFile
from os.path import getsize

# Part 1

In [2]:
#creating an array of numbers
np.random.default_rng(10)
array = np.random.randint(0, 10, size=(3,4))
print(array)

[[6 8 1 0]
 [8 4 5 0]
 [6 4 1 5]]


In [3]:
#saving as a csv file and creating it as a Dataframe
np.savetxt('array.csv', array, delimiter=',', fmt='%d', header='Column1,Column2,Column3')
df = pd.DataFrame(array)
print(df)

   0  1  2  3
0  6  8  1  0
1  8  4  5  0
2  6  4  1  5


In [4]:
# Whrite the dataframe int a csv file
df.to_csv('pd.csv', float_format='%.2f', na_rep='NAN!')

# Part 2

In [5]:
##create a 365 by 4 array of random numbers
np.random.default_rng(42)
array2 = np.random.randint(0, 10, size=(365,4))
print(array2)

[[7 7 9 2]
 [3 9 8 7]
 [1 0 2 6]
 ...
 [9 5 3 6]
 [2 9 1 7]
 [9 5 9 2]]


In [6]:
#saving the array and checking its size
temp = NamedTemporaryFile()
np.savetxt(temp, array2, delimiter=',')
print("size of file: ", getsize(temp.name))

size of file:  32400


In [8]:
#saving into a numpy format and reading file size and shape
np.save(temp, array2)
temp.seek(0)
load = np.load(temp)
print("Shape: ", load.shape)
print("Size of .npy file: ", getsize(temp.name))

Shape:  (365, 4)
Size of .npy file:  42468


In [9]:
#Creating a DataFrame from second array and writting it to a pickle, then retrieve it from the pickle. However, I am recieving a permission denied error so I can not retrieve it nor print the size
df2 = pd.DataFrame(array2)
df2.to_pickle(temp.name)
print("Size of pickle data: ", getsize(temp.name))
print("DF from pickle: \n", pd.read_pickle(temp.name))

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\isisV\\AppData\\Local\\Temp\\tmpn8xis8x4'

In [10]:
pip install openpyxl xlsxwriter xlrd

Note: you may need to restart the kernel to use updated packages.


# Part 3

In [14]:
#Saving the 365 by 4 array into an excel file and printing results
filename = 'excel_demo.xlsx'
df2.to_excel(filename, sheet_name='Random_data')
print(pd.read_excel(filename, 'Random_data'))

     Unnamed: 0  0  1  2  3
0             0  7  7  9  2
1             1  3  9  8  7
2             2  1  0  2  6
3             3  3  2  6  5
4             4  1  6  0  4
..          ... .. .. .. ..
360         360  6  9  4  3
361         361  5  8  8  6
362         362  9  5  3  6
363         363  2  9  1  7
364         364  9  5  9  2

[365 rows x 5 columns]


# Part 4

In [23]:
import json
#Json string
json_string = '''{"country":"Netherlands",
        "dma_code":"0",
        "timezone":"Europe\/Amsterdam",
        "area_code":"0",
        "ip":"46.19.37.108",
        "asn":"AS196752",
        "continent_code":
        "EU","isp":"Tilaa V.O.F.",
        "longitude":5.75,
        "latitude":52.5,
        "country_code":"NL",
        "country_code3":"NLD"}'''

#parsing the data using loads()        
data1 = json.loads(json_string)
print( "country: ", data1["country"])

country:  Netherlands


In [25]:
#overwritting value country
data1["country"] = "Brazil"
print (json.dumps(data1))

{"country": "Brazil", "dma_code": "0", "timezone": "Europe/Amsterdam", "area_code": "0", "ip": "46.19.37.108", "asn": "AS196752", "continent_code": "EU", "isp": "Tilaa V.O.F.", "longitude": 5.75, "latitude": 52.5, "country_code": "NL", "country_code3": "NLD"}


# Part 5

In [30]:
#creating a pandas series
data2 = pd.read_json(json_string, typ='series')
#changing the country value
data2["country"] = "Brazil"
#printing results
print(data2.to_json)

<bound method NDFrame.to_json of country                     Brazil
dma_code                         0
timezone          Europe/Amsterdam
area_code                        0
ip                    46.19.37.108
asn                       AS196752
continent_code                  EU
isp                   Tilaa V.O.F.
longitude                     5.75
latitude                      52.5
country_code                    NL
country_code3                  NLD
dtype: object>


# Part 6

Follow along:

In [1]:
from bs4 import BeautifulSoup
import re

In [4]:
#open file
soup = BeautifulSoup(open('loremIpsum.html'))
#print first div
print("First div \n.", soup.div)

First div 
. <div class="tile">
<h4>Development</h4>
     0.10.1 - July 2014<br/>
</div>


In [5]:
#print class atrribute
print("First div class", soup.div['class'])

First div class ['tile']


In [6]:
#print the next attribute
print("First dfn text", soup.dl.dt.dfn.text)

First dfn text Quare attende, quaeso.


In [8]:
#looping through hyperlinks of document
for link in soup.find_all('a'):
   print("Link text", link.string, "URL", link.get('href'))

# looping through hyperlinks omitting find_all
for i, div in enumerate(soup('div')):
   print(i, div.contents)

#Div with id=official
official_div = soup.find_all("div", id="official")
print("Official Version", official_div[0].contents[2].strip())

#Get number of div tags with a defined class attribute
print("# elements with class", len(soup.find_all(class_=True)))

#find the number of tags with the class tile
tile_class = soup.find_all("div", class_="tile")
print("# Tile classes", len(tile_class))

#matching all div tags
print("# Divs with class containing tile", len(soup.find_all("div", class_=re.compile("tile"))))

#matching the div elements with the notile class
print("Using CSS selector\n", soup.select('div.notile'))

#Selecting first two list items in an ordered list
print("Selecting ordered list list items\n", soup.select("ol > li")[:2])
#Selecting second list item
print("Second list item in ordered list", soup.select("ol > li:nth-of-type(2)"))
#finding all text nodes containing the strin 2014
print("Searching for text string", soup.find_all(text=re.compile("2014")))

Link text loripsum.net URL http://loripsum.net/
Link text Poterat autem inpune; URL http://loripsum.net/
Link text Is es profecto tu. URL http://loripsum.net/
0 ['\n', <h4>Development</h4>, '\n     0.10.1 - July 2014', <br/>, '\n']
1 ['\n', <h4>Official Release</h4>, '\n     0.10.0 June 2014', <br/>, '\n']
2 ['\n', <h4>Previous Release</h4>, '\n     0.09.1 June 2013', <br/>, '\n']
Official Version 0.10.0 June 2014
# elements with class 3
# Tile classes 2
# Divs with class containing tile 3
Using CSS selector
 [<div class="notile">
<h4>Previous Release</h4>
     0.09.1 June 2013<br/>
</div>]
Selecting ordered list list items
 [<li>Cur id non ita fit?</li>, <li>In qua si nihil est praeter rationem, sit in una virtute finis bonorum;</li>]
Second list item in ordered list [<li>In qua si nihil est praeter rationem, sit in una virtute finis bonorum;</li>]
Searching for text string ['\n     0.10.1 - July 2014', '\n     0.10.0 June 2014']
